/*=============================================================================
 * Copyright 2017 Bo Shao. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *	
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
==============================================================================*/
package net.papayachat.chatservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChatService", 
				  targetNamespace = "http://papayachat.net/ChatService", 
				  wsdlLocation = "http://localhost/wsdl/ChatService.xml")
public class ChatService extends Service {
    private final static URL CHATSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHATSERVICE_EXCEPTION;
    private final static QName CHATSERVICE_QNAME = 
			new QName("http://papayachat.net/ChatService", "ChatService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/ChatService.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHATSERVICE_WSDL_LOCATION = url;
        CHATSERVICE_EXCEPTION = e;
    }

    public ChatService() {
        super(__getWsdlLocation(), CHATSERVICE_QNAME);
    }

    public ChatService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHATSERVICE_QNAME, features);
    }

    public ChatService(URL wsdlLocation) {
        super(wsdlLocation, CHATSERVICE_QNAME);
    }

    public ChatService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHATSERVICE_QNAME, features);
    }

    public ChatService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChatService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChatServicePortType
     */
    @WebEndpoint(name = "ChatServicePort")
    public ChatServicePortType getChatServicePort() {
        return super.getPort(new QName("http://papayachat.net/ChatService", "ChatServicePort"), 
				ChatServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  
	 *	   Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChatServicePortType
     */
    @WebEndpoint(name = "ChatServicePort")
    public ChatServicePortType getChatServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://papayachat.net/ChatService", "ChatServicePort"), 
				ChatServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHATSERVICE_EXCEPTION!= null) {
            throw CHATSERVICE_EXCEPTION;
        }
        return CHATSERVICE_WSDL_LOCATION;
    }
}