/*=============================================================================
 * Copyright 2017 Bo Shao. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *	
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
==============================================================================*/
package net.papayachat.chatservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChatServicePortType", targetNamespace = "http://papayachat.net/ChatService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChatServicePortType {
    /**
     * 
     * @param parameters
     * @return
     *     returns net.papayachat.chatservice.SessionSentence
     */
    @WebMethod(action = "http://papayachat.net/ChatService/reply")
    @WebResult(name = "SessionSentence", 
			   targetNamespace = "http://papayachat.net/ChatService", 
			   partName = "returns")
    public SessionSentence reply(
        @WebParam(name = "params", 
				  targetNamespace = "http://papayachat.net/ChatService", 
				  partName = "parameters")
        ParamsTypes parameters);
}